name: update homepage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core:2.9

      - name: running make script
        run: pandoc -s --template docs/template.html -c docs/style.css README.md -o docs/index.html

